os: windows
language: C++
branches:
  only:
  - master
before_install:
  - wget -q https://download.qt.io/official_releases/qt/5.13/5.13.2/qt-opensource-windows-x86-5.13.2.exe
install:
  - choco install golang
  - choco install yasm
  - ./qt-opensource-windows-x86-5.13.2.exe --script ./.ci/qt_installer_windows.qs
script:
  - mkdir build
  - cd build
  - setx GOROOT "c:\Go"
  - setx path "%path%;C:\Qt\5.13.2\msvc2017\bin;C:\Go\bin;C:\ProgramData\chocolatey\lib\yasm\tools"
  - set GOROOT="c:\Go"
  - set PATH="%PATH%;C:\Qt\5.13.2\msvc2017\bin;C:\Go\bin;C:\ProgramData\chocolatey\lib\yasm\tools"
  - qmake -qt=qt5 -v
  - qmake -qt=qt5
  - make